name: master
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0' # 00:00 Sunday

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.0.0, stable]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose
